export const Colors = {
    orange: '#FF9A66',
    violet: '#6A66B8',
    veryLightOrange: '#FFF7F3',
    bottomBackground: '#FFE5CF',
    violetText: '#544FB3',
    grayText: '#6B6475',
    inputBackground: '#6A66B8',
    WhiteText: '#FFFFFF',
    grayPlaceholder: '#666666',
    gray: '#767676',
    black: '#000000',
    white: '#FFFFFF',
    palePurple : '#81458F',
    lightOrange: "#FF9A66",
    red: '#FF2626',
    buttonBackgroundViolet: '#584EAF',
    whiteLittleGray: "#DDDDDD",
    transparentBlack: "rgba(0, 0, 0, 0.5)",
    purpleBackground: '#2D1C56',
    lavender: '#A99DD9',
    brightOrange: '#FF7630',
    darkerWhite: '#EEEEEE',
    fondHaut: '#FFF7F3',
    fondBas: '#FFE5CF',
    texteViolet: '#544FB3',
    texteGris: '#6B6475',
    champFond: '#6A66B8',
    lightViolet: '#A9A7ED',
    orangeVeryLight: '#FFEFDF',
    lightPurple: '#CDCCEB',
    orangeWhite: '#FFF5F0',
    colorCream: '#FFF8F2',
    grayToWhite: '#F5F5F5',
    grayBorder: '#CCCCCC',
    modernGray: '#F8F9FA',
    modernMoreGray: '#F1F3F5',
};
