import { StyleSheet } from 'react-native';
import { Colors } from '@/constants/colors'

export const styles = StyleSheet.create({
    container: {
        flex: 1,
        flexDirection: 'row',
        backgroundColor: Colors.white,
    },
    content: {
        flex: 1,
        padding: 20,
    },
    desktopLayout: {
        flexDirection: 'row',
        gap: 20,
        alignItems: 'flex-start',
        maxWidth: '100%'
    },
    pageTitle: {
        fontSize: 28,
        fontWeight: 'bold',
        color: Colors.black,
        marginLeft: 20,
        marginBottom: 2,
    },
    subtitle: {
        fontSize: 20,
        fontWeight: 'bold',
        color: Colors.black,
    },
    text:{
        fontSize: 12,
        color: Colors.grayText,
        marginBottom: 12,
        marginLeft: 20,
    },
    missionDetail: {
        fontSize: 14,
        color: Colors.grayPlaceholder,
    },
    categoryContainer: {
        marginTop: 8,
        alignSelf: 'flex-start',
    },
    actionsSection: {
        flexDirection: 'row',
        gap: 20,
        alignItems: 'center',
    },
    participantsContainer: {
        flexDirection: 'column',
        alignItems: 'center',
        gap: 4,
        marginLeft: 10,
    },
    imageSection: {
        justifyContent: 'center',
        alignItems: 'center',
        gap: 8,
    },
    participantsIcon: {
        width: 50,
        height: 50,
        resizeMode: 'contain',
    },
    participantsText: {
        fontSize: 16,
        fontWeight: '600',
        color: Colors.black,
        textAlign: 'center',
    },
    linkText: {
        fontSize: 14,
        color: '#4A90E2',
        textDecorationLine: 'underline',
        marginBottom: 24,
    },
    leftColumn: {
        flex: 1,
        minWidth: 310,
        maxWidth: 450,
        marginRight: 20,
    },
    rightColumn: {
        flex: 1,
        minWidth: 0,
        gap: 20,
    },
    calendar: {
        backgroundColor: Colors.white,
        borderRadius: 12,
        padding: 20,
        shadowColor: Colors.black,
        shadowOffset: { width: 0, height: 2 },
        shadowOpacity: 0.1,
        shadowRadius: 4,
        maxWidth: '100%',
        width:'100%',
    },
    calendarHeader: {
        alignItems: 'center',
        marginBottom: 16,
    },
    calendarMonth: {
        fontSize: 18,
        fontWeight: '600',
        color: Colors.white,
        backgroundColor: Colors.brightOrange,
        paddingVertical: 8,
        paddingHorizontal: 24,
        borderRadius: 20,
    },
    calendarWeekDays: {
        flexDirection: 'row',
        marginBottom: 12,
    },
    weekDay: {
        flex: 1,
        textAlign: 'center',
        fontSize: 12,
        fontWeight: '600',
        color: Colors.brightOrange,
    },
    calendarDays: {
        flexDirection: 'row',
        flexWrap: 'wrap',
    },
    calendarDay: {
        width: `${100 / 7}%`,
        height: 40,
        justifyContent: 'center',
        alignItems: 'center',
    },
    calendarDayEmpty: {
        opacity: 0.3,
    },
    calendarDayText: {
        fontSize: 14,
        color: Colors.black,
    },
    calendarEvent: {
        flexDirection: 'row',
        alignItems: 'center',
        marginTop: 16,
        padding: 12,
        backgroundColor: Colors.orangeWhite,
        borderRadius: 8,
        gap: 8,
    },
    eventTime: {
        fontSize: 14,
        fontWeight: '600',
        color: Colors.black,
    },
    eventTitle: {
        fontSize: 14,
        color: Colors.black,
        flex: 1,
    },
    calendarDayToday: {
        backgroundColor: Colors.brightOrange,
        borderWidth: 2,
        borderColor: Colors.white,
        borderRadius: 20,
    },
    calendarDaySelected: {
        backgroundColor: Colors.orangeVeryLight,
        borderWidth: 2,
        borderColor: Colors.brightOrange,
        borderRadius: 20,
    },
    missionsSection: {
        marginTop: 16,
        padding: 12,
        minHeight: 20,
    },
    noEventsText: {
        fontSize: 14,
        color: Colors.grayPlaceholder,
        textAlign: 'center',
        fontStyle: 'italic',
    },
    loadingText: {
        fontSize: 14,
        color: Colors.grayPlaceholder,
        textAlign: 'center',
    },
    statsCard: {
        backgroundColor: Colors.white,
        borderRadius: 12,
        padding: 20,
        alignItems: 'center',
        shadowColor: Colors.black,
        shadowOffset: { width: 0, height: 2 },
        shadowOpacity: 0.1,
        shadowRadius: 4,
    },
    statsNumber: {
        fontSize: 48,
        fontWeight: 'bold',
        color: Colors.brightOrange,
        marginBottom: 12,
    },
    statsButton: {
        backgroundColor: Colors.brightOrange,
        width: 60,
        height: 60,
        borderRadius: 30,
        justifyContent: 'center',
        alignItems: 'center',
    },
    statsIcon: {
        fontSize: 24,
    },
    descriptionCard: {
        backgroundColor: Colors.white,
        borderRadius: 12,
        padding: 20,
        shadowColor: Colors.black,
        shadowOffset: { width: 0, height: 2 },
        shadowOpacity: 0.1,
        shadowRadius: 4,
    },
    cardTitle: {
        fontSize: 18,
        fontWeight: '600',
        color: Colors.black,
        marginBottom: 16,
        alignSelf: 'center',
    },
    textArea: {
        backgroundColor: Colors.white,
        borderWidth: 1,
        borderColor: Colors.whiteLittleGray,
        borderRadius: 8,
        padding: 12,
        fontSize: 14,
        color: Colors.black,
        height: 120,
        textAlignVertical: 'top',
        marginBottom: 12,
    },
    addressCard: {
        backgroundColor: Colors.white,
        borderRadius: 12,
        padding: 20,
        shadowColor: Colors.black,
        shadowOffset: { width: 0, height: 2 },
        shadowOpacity: 0.1,
        shadowRadius: 4,
    },
    addressGroup: {
        flexDirection: 'row',
        justifyContent: 'flex-end',
        marginBottom: 12,
    },
    infoIconAddress: {
        width: 32,
        height: 32,
        borderRadius: 16,
        backgroundColor: '#4A90E2',
        justifyContent: 'center',
        alignItems: 'center',
    },
    formRow: {
        flexDirection: 'row',
    },
    menuGrid: {
        alignItems: 'center',
    },
    menuCard: {
        margin: 10,
    },
    menuIconContainer: {
        width: 150,
        height: 150,
        borderRadius: 30,
        backgroundColor: Colors.orangeVeryLight,
        justifyContent: 'center',
        alignItems: 'center',
    },
    menuIcon: {
        justifyContent: 'center',
        alignItems: 'center',
        width: '50%',
        height: '50%',
        resizeMode: 'contain',
        marginBottom: 10,
    },
    menuLabel: {
        fontSize: 15,
        fontWeight: '600',
        color: '#333',
        textAlign: 'center',
    },
    statsCardMobile: {
        marginBottom: 30,
        alignItems: 'center',
    },
    profilIcon: {
        width: 200,
        height: 200,
        resizeMode: 'contain',
    },
    separatorLine: {
        height: 2,
        backgroundColor: Colors.violet,
        alignSelf: 'stretch',
    },
    card: {
        backgroundColor: Colors.white,
        borderRadius: 12,
        padding: 20,
        marginBottom: 20,
        shadowColor: Colors.black,
        shadowOffset: { width: 0, height: 2 },
        shadowOpacity: 0.1,
        shadowRadius: 4,
        elevation: 3,
    },
    cardHeader: {
        flexDirection: 'row',
        justifyContent: 'space-between',
        alignItems: 'center',
        marginBottom: 16,
    },
    formGroup: {
        marginBottom: 16,
    },
    label: {
        fontSize: 14,
        color: Colors.violet,
        fontWeight: '600',
        marginBottom: 6,
    },
    input: {
        backgroundColor: Colors.white,
        borderWidth: 1,
        borderColor: Colors.whiteLittleGray,
        borderRadius: 8,
        padding: 12,
        fontSize: 14,
        color: Colors.black,
    },
    infoIcon: {
        width: 32,
        height: 32,
        borderRadius: 16,
        backgroundColor: Colors.violet,
        justifyContent: 'center',
        alignItems: 'center',
    },
    infoIconImage: {
        width: 25,
        height: 25,
        justifyContent: 'center',
        alignItems: 'center',
        resizeMode: 'contain',
    },
    buttonRow: {
        flexDirection: 'row',
        justifyContent: 'flex-end',
        gap: 12,
    },
    smallButton: {
        width: 40,
        height: 40,
        borderRadius: 20,
        justifyContent: 'center',
        alignItems: 'center',
    },
    editButton: {
        backgroundColor: Colors.lightOrange,
        alignSelf: 'flex-end',
    },
    saveButton: {
        backgroundColor: Colors.lightOrange,
    },
    cancelButton: {
        backgroundColor: Colors.lightOrange,
    },
    buttonText: {
        fontSize: 20,
        fontWeight: 'bold',
    },
    fileSection: {
        marginTop: 10,
        marginBottom: 14,
        padding: 12,
        backgroundColor: Colors.orangeWhite,
        borderRadius: 8,
        borderWidth: 1,
        borderColor: Colors.brightOrange,
    },
    warningText: {
        fontSize: 14,
        color: Colors.brightOrange,
        fontWeight: '600',
        marginBottom: 12,
    },
    uploadButton: {
        backgroundColor: Colors.violet,
        paddingVertical: 12,
        paddingHorizontal: 16,
        borderRadius: 8,
        alignItems: 'center',
    },
    uploadButtonText: {
        color: Colors.white,
        fontSize: 14,
        fontWeight: '600',
    },
    fileName: {
        fontSize: 12,
        color: Colors.grayText,
        marginTop: 8,
        fontStyle: 'italic',
    },
});