export type ProfileData = {
    id_volunteer: number;
    id_admin: number;
    id_asso: number;
    picture: any;
    last_name: string;
    first_name: string;
    phone_number: string;
    birthdate: string;
    skills: string;
    address: string;
    zip_code: string;
    bio: string;
    email: string;
    username: string;
    name: string;
    country: string;
    rna_code: string;
    company_name: string;
    password: string;
    confirmPassword: string;
};